### ISSUE TITLE
ValidatorFX & Jdeps

### ISSUE THREAD

**Issue by AntoninHuaut** [effad/ValidatorFX#24]
Hi,
Are there any plans to make ValidatorFX modular? 
Due to its non-modularity, ValidatorFX is incompatible with the java jdeps command, and it is therefore impossible to create a specific JRE for each application.

Thanks

**Comment by effad** [comment]
Thank you for the PR that you sent. I'll try to release a new version ASAP.

**Comment by effad** [comment]
I just released 0.3.1, which contains your PR fot this issue.

**Comment by effad** [comment]
Turns out this PR messed up eclipse badly. When I try to import ValidatorFX, there's errors like 
"javafx.base cannot be resolved to a module"
in module-info.java

This is most likely (again) a problem with Eclipse buildship. @AntoninHuaut If you have any pointers / hints concerning the eclipse problem, I'd be grateful.

**Comment by AntoninHuaut** [comment]
I haven't used eclipse for a few years, I only use Intellij IDEA.
In my memory, I used to use a fx plugin for eclipse: [e(fx)clipse](https://www.eclipse.org/efxclipse/install.html).

**Comment by effad** [comment]
Since this is not really a problem of ValidatorFX but eclipse I've switched to Intellij for ValidatorFX development. Closing this issue again.
