### ISSUE TITLE
Button with Tooltip Wrapper disappear

### ISSUE THREAD

**Issue by goshik81** [effad/ValidatorFX#44]
Hi.
I am trying to use validator to disable button.

`TooltipWrapper<Button> saveWrapper = new TooltipWrapper<>(
                btn_save,
                validator.containsErrorsProperty(),
                Bindings.concat("Cant's save to DataBase:\n", validator.createStringBinding())
        );`

But button has disappeared.

![image](https://github.com/user-attachments/assets/c5be3f9c-98d7-41f2-acca-42cad9cb320c)
[ButtonTest.zip](https://github.com/user-attachments/files/17597577/ButtonTest.zip)

**Comment by effad** [comment]
You are creating `TooltipWrapper<Button> saveWrapper` within `protected void initialize` but after the method is run, there is no reference to saveWrapper anymore, thus the Java Garbage Collector will collect the wrapper (and the button it contains, since TooltipWrapper will set the parent of the wrapped object to itself).

What you do here is you basically rip the button from the FXML out of the scene graph and put it into the wrapper which is used nowhere.

You have to ensure that your wrapper is properly integrated into the scene by getting the parent of `btn_test` and adding 
`saveWrapper` to it's children instead of btn_test itself.
Not sure about the best way to achieve this with FXML (I never use FXML), but either your FXML must already contain a TooltipWrapper instance instead of a Button instance or you have to get hold of the parent container of `btn_test` and manually add `saveWrapper` as child of it.

**Comment by goshik81** [comment]
I don't think the problem is in GC.
After initialization I can successfully access the button (which means it still exists).
However, I did not see where "TooltipWrapper" is added to the scene.

But if the code is written like this:
`        Node btnParent = btn_test.getParent();

        TooltipWrapper<Button> saveWrapper = new TooltipWrapper<>(
                btn_test,
                validator.containsErrorsProperty(),
                Bindings.concat("Text field has errors:\n", validator.createStringBinding())
        );

        ((VBox)btnParent).getChildren().add(saveWrapper);`

The button is displayed

**Comment by effad** [comment]
Exactly. TooltipWrapper does not add itself to the scene automatically, you have to do this yourself.

**Comment by goshik81** [comment]
Oh. Thanks. I didn't see this in readme.
